services:
  # MySQL
  db:
    container_name: onseju-order
    image: mysql:8.0
    command: mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --wait_timeout=30
      --interactive_timeout=600
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onseju-order
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_MAX_CONNECTIONS: 200
      LANG: ko_kr.utf-8
      LC_ALL: ko_kr.utf-8
    ports:
      - "3306:3306"
  rabbitMq:
    container_name: onseju-rabbitmq
    image: rabbitmq:4.0.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 40s
    networks:
      - onseju-network
      
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  rabbitmq-data:
  rabbitmq_logs:

networks:
  onseju-network:
    driver: bridge