name: CICD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: false
          cache-overwrite-existing: true

      - name: Build and Test
        run: ./gradlew build test --parallel

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            **/build/test-results/**/*.xml

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/build/reports/tests/
            **/build/test-results/
          retention-days: 7

      - name: Build JAR
        run: ./gradlew bootJar

  docker:
    needs: build
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/onseju-app:order
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/onseju-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/onseju-app:buildcache,mode=max

  deploy:
    needs: docker
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.ref == 'refs/heads/develop' && github.event_name == 'push')
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create env file
        run: |
          cat > env-config.sh << 'EOF'
          cat > /tmp/order-service.env << 'INNEREOF'
          DB_URL=${{ secrets.DB_URL }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}
          RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
          GOOGLE_TOKEN_URI=${{ secrets.GOOGLE_TOKEN_URI }}
          GOOGLE_USER_INFO=${{ secrets.GOOGLE_USER_INFO }}
          USER_SERVICE_BASE_URL=${{ secrets.USER_SERVICE_BASE_URL }}
          KI_APPROVAL_URL=${{ secrets.KI_APPROVAL_URL }}
          KI_GRANT_TYPE=${{ secrets.KI_GRANT_TYPE }}
          KI_APP_KEY_1=${{ secrets.KI_APP_KEY_1 }}
          KI_SECRET_KEY_1=${{ secrets.KI_SECRET_KEY_1 }}
          KI_APP_KEY_2=${{ secrets.KI_APP_KEY_2 }}
          KI_SECRET_KEY_2=${{ secrets.KI_SECRET_KEY_2 }}
          KI_STOCK_WS_URL=${{ secrets.KI_STOCK_WS_URL }}
          KI_HOGA_WS_URL=${{ secrets.KI_HOGA_WS_URL }}
          INNEREOF
          chmod 600 /tmp/order-service.env
          EOF
          chmod +x env-config.sh

      - name: Deploy to EC2
        env:
          EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --instance-ids $EC2_INSTANCE_ID \
            --document-name "AWS-RunShellScript" \
            --parameters commands="[
              \"echo \\\"${{ secrets.DOCKERHUB_TOKEN }}\\\" | docker login -u \\\"${{ secrets.DOCKERHUB_USERNAME }}\\\" --password-stdin\",
              \"docker pull ${{ secrets.DOCKERHUB_USERNAME }}/onseju-app:order\",
              \"docker stop order-service || true\",
              \"docker rm order-service || true\",
              \"$(cat env-config.sh)\",
              \"docker run -d --name order-service --restart always -p 8081:8081 --env-file /tmp/order-service.env ${{ secrets.DOCKERHUB_USERNAME }}/onseju-app:order\",
              \"docker image prune -af --filter \\\"until=24h\\\"\",
              \"rm /tmp/order-service.env\"
            ]"

      - name: Deployment notification
        if: success()
        run: echo "주문 서비스가 성공적으로 배포되었습니다."
